name: Create Report
on:
  push:
    branches: [ "*"]
    paths-ignore:
      - README.md

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Generate Report
        run: cargo run --package aoc --bin aoc --release > report.log
      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: Report
          path: report.log
      - name: Print Report
        run: cat report.log
